name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Pull repository
      uses: appleboy/ssh-action@master
      with:
        HOST: 165.232.68.134
        USERNAME: "root"
        PASSWORD: "2022@Area"
        PORT: 22
        script: ./deploy.sh
